[package]
name = "aria2-wrapper"
version = "0.1.1"
edition = "2024"

[profile.release]
lto = true

[dependencies]
url = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
toml = "0.8"
dirs = "6.0.0"
