[package]
name = "aria2-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
url = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }
toml = "0.8"
dirs = "6.0.0"
